# Generated by Django 5.0.1 on 2024-01-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=400)),
                ('product_image', models.ImageField(upload_to='productos/')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('product_stock', models.IntegerField()),
            ],
        ),
    ]
