# Generated by Django 5.0.1 on 2024-01-18 22:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_detallepedido_product_product_dateadded_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleproducto',
            name='detalle_pedido',
        ),
        migrations.RemoveField(
            model_name='detalleproducto',
            name='product',
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_paymethod',
            field=models.CharField(choices=[('deb', 'DEBITO'), ('cred', 'CREDITO'), ('trans', 'TRANSFERENCIA')], default='DEBITO', max_length=20),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrito_creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('carrito_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('carrito_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.carrito')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_calle', models.CharField(max_length=100)),
                ('dir_ciudad', models.CharField(max_length=100)),
                ('dir_pais', models.CharField(max_length=100)),
                ('dir_codigopostal', models.IntegerField()),
                ('dir_type', models.CharField(choices=[('billing', 'FACTURACIÓN'), ('envio', 'ENVÍO')], default='FACTURACIÓN', max_length=20)),
                ('dir_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_dirbill',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_dirbill', to='shop.direccion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_direnvio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_direnvio', to='shop.direccion'),
        ),
        migrations.CreateModel(
            name='ProductosPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_en_compra', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pedido_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.pedido')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.DeleteModel(
            name='DetalleProducto',
        ),
    ]
