# Generated by Django 5.0.1 on 2024-01-25 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_extradatauser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('herramientas', 'Herramientas'), ('maquillaje', 'Maquillaje'), ('skincare', 'Skincare'), ('esponjas', 'Esponjas'), ('brochas', 'Brochas'), ('limpiadores', 'Limpiadores'), ('rostro', 'Rostro'), ('ojos', 'Ojos'), ('labios', 'Labios'), ('hidratantes', 'Hidratantes'), ('limpiadores', 'Limpiadores')], max_length=20)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productcategory')),
            ],
        ),
    ]
