# Generated by Django 5.0.1 on 2024-01-25 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.productcategory'),
            preserve_default=False,
        ),
    ]
