# Generated by Django 5.0.1 on 2024-02-06 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_productcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_subcategory',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='product_subcategory', to='shop.productcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='shop.productcategory'),
        ),
    ]
