# Generated by Django 5.0.1 on 2024-02-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_product_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='dir_pais',
        ),
        migrations.AlterField(
            model_name='direccion',
            name='dir_type',
            field=models.CharField(choices=[('billing', 'FACTURACION'), ('envio', 'ENVIO')], default='FACTURACIÓN', max_length=20),
        ),
    ]
