# Generated by Django 5.0.1 on 2024-02-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_direccion_dir_pais_alter_direccion_dir_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='dir_provincia',
            field=models.CharField(default='Cordoba', max_length=100),
        ),
    ]
