# Generated by Django 5.0.1 on 2024-02-16 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_direccion_dir_provincia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='dir_type',
        ),
    ]
