# Generated by Django 5.0.1 on 2024-03-02 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_direccion_dir_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='dir_user',
        ),
        migrations.AddField(
            model_name='extradatauser',
            name='user_dir',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.direccion'),
            preserve_default=False,
        ),
    ]
